// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
    [KeyType in keyof T]: T[KeyType];
};
/** Content for Test documents */
interface TestDocumentData {
    /**
     * testtitle field in *Test*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: test.testtitle
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    testtitle: prismicT.KeyTextField;
    /**
     * testdescription field in *Test*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: test.testdescription
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    testdescription: prismicT.RichTextField;
    /**
     * testfeatureimage field in *Test*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: test.testfeatureimage
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    testfeatureimage: prismicT.ImageField<never>;
    /**
     * testpublished field in *Test*
     *
     * - **Field Type**: Date
     * - **Placeholder**: *None*
     * - **API ID Path**: test.testpublished
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/date
     *
     */
    testpublished: prismicT.DateField;
}
/**
 * Test document from Prismic
 *
 * - **API ID**: `test`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TestDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<TestDocumentData>, "test", Lang>;
/** Content for trendings documents */
interface TrendingsDocumentData {
    /**
     * title field in *trendings*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: trendings.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * freatureImg field in *trendings*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: trendings.freatureimg
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    freatureimg: prismicT.ImageField<never>;
    /**
     * desc field in *trendings*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: trendings.desc
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    desc: prismicT.KeyTextField;
    /**
     * published field in *trendings*
     *
     * - **Field Type**: Date
     * - **Placeholder**: *None*
     * - **API ID Path**: trendings.published
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/date
     *
     */
    published: prismicT.DateField;
}
/**
 * trendings document from Prismic
 *
 * - **API ID**: `trendings`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TrendingsDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<TrendingsDocumentData>, "trendings", Lang>;
export type AllDocumentTypes = TestDocument | TrendingsDocument;
declare module "@prismicio/client" {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
    }
    namespace Content {
        export type { TestDocumentData, TestDocument, TrendingsDocumentData, TrendingsDocument, AllDocumentTypes };
    }
}
